name: salon_admin_app
version: 2.0.0+5
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  fl_chart: ^0.69.0
  geolocator: ^13.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_full.png"
  adaptive_icon_background: "#0E7C6B"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: AppSans
      fonts:
        - asset: assets/fonts/AppSans.ttf
